export const BASE_COST = [0,50,100,200,500,1000,2000,5000,10000,20000,50000,100000,200000,500000,1000000,2000000,5000000];

export const ASTROS = {
    Arid:{
        Metal:2,
        Gas:2,
        Crystals:0,
        Fertility:5,
        Area_planet:95,
        Area_moon:83
    },
    Asteroid:{
        Metal:3,
        Gas:1,
        Crystals:2,
        Fertility:4,
        Area_planet:0,
        Area_moon:65
    },
    Craters:{
        Metal:3,
        Gas:1,
        Crystals:1,
        Fertility:4,
        Area_planet:86,
        Area_moon:75
    },
    Crystalline:{
        Metal:2,
        Gas:1,
        Crystals:3,
        Fertility:4,
        Area_planet:80,
        Area_moon:71
    },
    Earthly:{
        Metal:2,
        Gas:2,
        Crystals:0,
        Fertility:6,
        Area_planet:85,
        Area_moon:75
    },
    Gaia:{
        Metal:2,
        Gas:2,
        Crystals:0,
        Fertility:6,
        Area_planet:90,
        Area_moon:79
    },
    Glacial:{
        Metal:1,
        Gas:2,
        Crystals:0,
        Fertility:5,
        Area_planet:95,
        Area_moon:83
    },
    Magma:{
        Metal:2,
        Gas:4,
        Crystals:0,
        Fertility:5,
        Area_planet:80,
        Area_moon:71
    },
    Metallic:{
        Metal:3,
        Gas:2,
        Crystals:1,
        Fertility:4,
        Area_planet:85,
        Area_moon:75
    },
    Oceanic:{
        Metal:1,
        Gas:2,
        Crystals:0,
        Fertility:6,
        Area_planet:80,
        Area_moon:71
    },
    Radioactive:{
        Metal:2,
        Gas:3,
        Crystals:0,
        Fertility:4,
        Area_planet:90,
        Area_moon:79
    },
    Rocky:{
        Metal:3,
        Gas:2,
        Crystals:0,
        Fertility:5,
        Area_planet:85,
        Area_moon:75
    },
    Toxic:{
        Metal:2,
        Gas:4,
        Crystals:0,
        Fertility:4,
        Area_planet:90,
        Area_moon:79
    },
    Tundra:{
        Metal:2,
        Gas:2,
        Crystals:0,
        Fertility:5,
        Area_planet:95,
        Area_moon:83
    },
    Volcanic:{
        Metal:2,
        Gas:4,
        Crystals:0,
        Fertility:5,
        Area_planet:80,
        Area_moon:71
    },
}

export const STRUCTURES = {
    Urban_structures:{
        COST:1,
        AREA:-1,
        ENERGY:0,
        POPULATION:0,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:false,
        ADVANCED:false
    },
    Solar_plants:{
        COST:1,
        AREA:-1,
        ENERGY:4,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:false,
        ADVANCED:false
    },
    Gas_plants:{
        COST:1,
        AREA:-1,
        ENERGY:0,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:false,
        ADVANCED:false
    },
    Fusion_plants:{
        COST:20,
        AREA:-1,
        ENERGY:4,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            ENERGY:6
        },
        ADVANCED:false
    },
    Antimatter_plants:{
        COST:2000,
        AREA:-1,
        ENERGY:10,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            ENERGY:20
        },
        ADVANCED:true
    },
    Obrital_plants:{
        COST:40000,
        AREA:-1,
        ENERGY:0,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            ENERGY:25
        },
        ADVANCED:true
    },
    Research_labs:{
        COST:1,
        AREA:-1,
        ENERGY:-1,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:false,
        ADVANCED:false
    },
    Metal_refineries:{
        COST:1,
        AREA:-1,
        ENERGY:-1,
        POPULATION:-1,
        ECONOMY:1,
        PRODUCTION:ASTROS,
        CONSTRUCTION:ASTROS,
        REQUIREMENTS:false,
        ADVANCED:false
    },
    Crystal_mines:{
        COST:2,
        AREA:-1,
        ENERGY:-1,
        POPULATION:-1,
        ECONOMY:ASTROS,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:false,
        ADVANCED:false
    },
    Robotic_factories:{
        COST:5,
        AREA:-1,
        ENERGY:-1,
        POPULATION:-1,
        ECONOMY:1,
        PRODUCTION:2,
        CONSTRUCTION:2,
        REQUIREMENTS:false,
        ADVANCED:false
    },
    Shipyards:{
        COST:5,
        AREA:-1,
        ENERGY:-1,
        POPULATION:-1,
        ECONOMY:1,
        PRODUCTION:2,
        CONSTRUCTION:0,
        REQUIREMENTS:false,
        ADVANCED:false
    },
    Orbital_shipyards:{
        COST:10000,
        AREA:0,
        ENERGY:-12,
        POPULATION:-1,
        ECONOMY:2,
        PRODUCTION:8,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            CYBERNETICS:2
        },
        ADVANCED:true
    },
    Spaceports:{
        COST:5,
        AREA:-1,
        ENERGY:-1,
        POPULATION:-1,
        ECONOMY:2,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:false,
        ADVANCED:false
    },
    Command_centers:{
        COST:20,
        AREA:-1,
        ENERGY:-1,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            COMPUTER:6
        },
        ADVANCED:false
    },
    Nanite_factories:{
        COST:80,
        AREA:-1,
        ENERGY:-2,
        POPULATION:-1,
        ECONOMY:2,
        PRODUCTION:4,
        CONSTRUCTION:4,
        REQUIREMENTS:{
            COMPUTER:10,
            LASER:6
        },
        ADVANCED:true
    },
    Android_factories:{
        COST:100,
        AREA:-1,
        ENERGY:-4,
        POPULATION:-1,
        ECONOMY:2,
        PRODUCTION:6,
        CONSTRUCTION:6,
        REQUIREMENTS:{
            ARTIFICAL_INTELLIGENCE:4
        },
        ADVANCED:true
    },
    Economic_centers:{
        COST:80,
        AREA:-1,
        ENERGY:-2,
        POPULATION:-1,
        ECONOMY:4,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            COMPUTER:10
        },
        ADVANCED:true
    },
    Terraform:{
        COST:80,
        AREA:5,
        ENERGY:0,
        POPULATION:0,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            COMPUTER:10,
            ENERGY:10
        },
        ADVANCED:true
    },
    Multilevel_platforms:{
        COST:10000,
        AREA:10,
        ENERGY:0,
        POPULATION:0,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            ARMOUR:22
        },
        ADVANCED:true
    },
    Orbital_base:{
        COST:2000,
        AREA:0,
        ENERGY:0,
        POPULATION:10,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            COMPUTER:20
        },
        ADVANCED:true
    },
    Jump_gate:{
        COST:5000,
        AREA:0,
        ENERGY:-8,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            WARP_DRIVE:12,
            ENERGY:20
        },
        ADVANCED:false
    },
    Biosphere_modification:{
        COST:20000,
        AREA:-1,
        ENERGY:-24,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            COMPUTER:24,
            ENERGY:24
        },
        ADVANCED:false
    },
    Capital:{
        COST:15000,
        AREA:-1,
        ENERGY:-12,
        POPULATION:-1,
        ECONOMY:10,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            TACHYON_COMMUNICATIONS:1
        },
        ADVANCED:false
    },
    Barracks:{
        COST:5,
        AREA:-1,
        ENERGY:0,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            LASER:1
        },
        ADVANCED:false
    },
    Laser_turrets:{
        COST:10,
        AREA:-1,
        ENERGY:-1,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            LASER:1
        },
        ADVANCED:false
    },
    Missile_turrets:{
        COST:20,
        AREA:-1,
        ENERGY:-1,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            MISSILES:1
        },
        ADVANCED:false
    },
    Plasma_turrets:{
        COST:100,
        AREA:-1,
        ENERGY:-2,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            PLASMA:1,
            ARMOUR:6
        },
        ADVANCED:false
    },
    Ion_turrets:{
        COST:256,
        AREA:-1,
        ENERGY:-3,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            ION:1,
            ARMOUR:10,
            SHIELDING:2
        },
        ADVANCED:false
    },
    Photon_turrets:{
        COST:1024,
        AREA:-1,
        ENERGY:-4,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            PHOTON:1,
            ARMOUR:14,
            SHIELDING:6
        },
        ADVANCED:false
    },
    Disruptor_turrets:{
        COST:4096,
        AREA:-1,
        ENERGY:-8,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            DISRUPTOR:1,
            ARMOUR:18,
            SHIELDING:8
        },
        ADVANCED:false
    },
    Deflection_shields:{
        COST:4096,
        AREA:-1,
        ENERGY:-8,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            ION:6,
            ARMOUR:10
        },
        ADVANCED:false
    },
    Planetary_shield:{
        COST:25000,
        AREA:-1,
        ENERGY:-16,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            ION:10,
            ARMOUR:14
        },
        ADVANCED:false
    },
    Planetary_ring:{
        COST:50000,
        AREA:0,
        ENERGY:-24,
        POPULATION:-1,
        ECONOMY:0,
        PRODUCTION:0,
        CONSTRUCTION:0,
        REQUIREMENTS:{
            PHOTON:10,
            ARMOUR:22,
            SHIELDING:12
        },
        ADVANCED:false
    },
}

export const TECHNOLOGIES = {
    ENERGY:{
        COST:2,
        LABS:1,
        REQUIREMENTS:false
    },
    COMPUTER:{
        COST:2,
        LABS:1,
        REQUIREMENTS:false
    },
    ARMOUR:{
        COST:4,
        LABS:2,
        REQUIREMENTS:false
    },
    LASER:{
        COST:4,
        LABS:2,
        REQUIREMENTS:{
            LASER:2
        }
    },
    MISSILES:{
        COST:8,
        LABS:4,
        REQUIREMENTS:{
            COMPUTER:4
        }
    },
    STELLAR_DRIVE:{
        COST:16,
        LABS:5,
        REQUIREMENTS:{
            ENERGY:6
        }
    },
    PLASMA:{
        COST:32,
        LABS:6,
        REQUIREMENTS:{
            ENERGY:6,
            LASER:4
        }
    },
    WARP_DRIVE:{
        COST:64,
        LABS:8,
        REQUIREMENTS:{
            ENERGY:8,
            STELLAR_DRIVE:4
        }
    },
    SHIELDING:{
        COST:128,
        LABS:10,
        REQUIREMENTS:{
            ENERGY:10
        }
    },
    ION:{
        COST:256,
        LABS:12,
        REQUIREMENTS:{
            ENERGY:12,
            LASER:10
        }
    },
    PHOTON:{
        COST:1024,
        LABS:16,
        REQUIREMENTS:{
            ENERGY:16,
            PLASMA:8
        }
    },
    ARTIFICAL_INTELLIGENCE:{
        COST:2048,
        LABS:18,
        REQUIREMENTS:{
            COMPUTER:20
        }
    },
    DISRUPTOR:{
        COST:4096,
        LABS:20,
        REQUIREMENTS:{
            ENERGY:20,
            LASER:18
        }
    },
    CYBERNETICS:{
        COST:8192,
        LABS:22,
        REQUIREMENTS:{
            ARTIFICAL_INTELLIGENCE:6
        }
    },
    TACHYON_COMMUNICATIONS:{
        COST:32768,
        LABS:24,
        REQUIREMENTS:{
            ENERGY:24,
            COMPUTER:24
        }
    },
    ANTI_GRAVITY:{
        COST:100000,
        LABS:26,
        REQUIREMENTS:{
            ENERGY:26,
            COMPUTER:26
        }
    },
}